# Generated by Django 4.2.4 on 2023-08-16 16:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("garagem", "0002_acessorio_cor_modelo_veiculo"),
    ]

    operations = [
        migrations.AddField(
            model_name="veiculo",
            name="acessorios",
            field=models.ManyToManyField(
                related_name="veiculos", to="garagem.acessorio"
            ),
        ),
    ]
